In [2]:
import wbdata
import world_bank_data as wb
import pycountry

import pandas as pd

from tqdm import tqdm 
import time

import missingno as msno

In [4]:
import sys
from pathlib import Path

# Add ../helper to sys.path
helper_path = Path(__file__).resolve().parent.parent / "helper"
sys.path.insert(0, str(helper_path))

from config_GAM2025 import gam_info

In [2]:

def is_country(entry):
    if entry['region']['value'] == 'Aggregates' or entry['incomeLevel']['value'] == 'Aggregates':
        return False
    if not entry['capitalCity']:
        return False
    return True
    
pop_data = []
# Fetch the list of countries
countries = wbdata.get_countries()
for country in tqdm(countries):

    if is_country(country):
        iso2_code = country['iso2Code']
        #print(f"{country['name']} ({country['id']})")
        
        # Define the indicator for population data
        indicator = 'SP.POP.TOTL'
        try:
            #df = wbdata.get_dataframe(indicators, country=iso2_code)
            df = wb.get_series(indicator, country=iso2_code).reset_index()
            df['ISO2'] = iso2_code
            pop_data.append(df)
        except Exception as e:
            print(f"Error fetching data for {country['name']} ({country['id']}): {e}")    
        time.sleep(2)
    
    else: 
        print(f"skipping: {country['name']}")

  0%|▎                                                                                          | 1/296 [00:02<11:41,  2.38s/it]

skipping: Africa Eastern and Southern

  1%|▉                                                                                          | 3/296 [00:04<07:44,  1.59s/it]

skipping: Africa
skipping: Africa Western and Central

  3%|██▍                                                                                        | 8/296 [00:12<08:16,  1.73s/it]

skipping: Arab World

  6%|█████▍                                                                                    | 18/296 [00:35<11:07,  2.40s/it]

skipping: East Asia & Pacific (IBRD-only countries)
skipping: Europe & Central Asia (IBRD-only countries)

  8%|███████▌                                                                                  | 25/296 [00:47<09:40,  2.14s/it]

skipping: IBRD countries classified as high income

 10%|████████▊                                                                                 | 29/296 [00:55<09:23,  2.11s/it]

skipping: Latin America & the Caribbean (IBRD-only countries)

 11%|█████████▋                                                                                | 32/296 [01:00<08:31,  1.94s/it]

skipping: Middle East & North Africa (IBRD-only countries)

 13%|███████████▌                                                                              | 38/296 [01:12<09:27,  2.20s/it]

skipping: Sub-Saharan Africa (IBRD-only countries)

 14%|████████████▍                                                                             | 41/296 [01:17<08:15,  1.94s/it]

skipping: Sub-Saharan Africa (IFC classification)

 15%|█████████████▍                                                                            | 44/296 [01:22<07:43,  1.84s/it]

skipping: East Asia and the Pacific (IFC classification)
skipping: Central Europe and the Baltics
skipping: Europe and Central Asia (IFC classification)

 16%|██████████████▌                                                                           | 48/296 [01:25<04:45,  1.15s/it]

skipping: Channel Islands

 18%|███████████████▊                                                                          | 52/296 [01:32<06:29,  1.60s/it]

skipping: Latin America and the Caribbean (IFC classification)
skipping: Middle East and North Africa (IFC classification)

 21%|██████████████████▌                                                                       | 61/296 [01:49<08:28,  2.16s/it]

skipping: South Asia (IFC classification)
skipping: Caribbean small states

 23%|████████████████████▋                                                                     | 68/296 [02:01<07:49,  2.06s/it]

skipping: East Asia & Pacific (IDA-eligible countries)
skipping: Europe & Central Asia (IDA-eligible countries)

 24%|█████████████████████▉                                                                    | 72/296 [02:06<06:07,  1.64s/it]

skipping: Latin America & the Caribbean (IDA-eligible countries)

 25%|██████████████████████▌                                                                   | 74/296 [02:09<05:49,  1.57s/it]

skipping: Middle East & North Africa (IDA-eligible countries)

 26%|███████████████████████                                                                   | 76/296 [02:11<05:24,  1.47s/it]

skipping: IDA countries in Sub-Saharan Africa not classified as fragile situations

 26%|███████████████████████▋                                                                  | 78/296 [02:14<05:00,  1.38s/it]

skipping: South Asia (IDA-eligible countries)
skipping: IDA countries in Sub-Saharan Africa classified as fragile situations
skipping: Sub-Saharan Africa (IDA-eligible countries)

 28%|████████████████████████▉                                                                 | 82/296 [02:16<03:39,  1.03s/it]

skipping: East Asia & Pacific (excluding high income)
skipping: Early-demographic dividend
skipping: East Asia & Pacific
skipping: Europe & Central Asia (excluding high income)
skipping: Europe & Central Asia

 30%|███████████████████████████                                                               | 89/296 [02:22<03:11,  1.08it/s]

skipping: Euro area

 32%|████████████████████████████▌                                                             | 94/296 [02:31<05:28,  1.62s/it]

skipping: European Union
skipping: Fragile and conflict affected situations

 34%|██████████████████████████████▎                                                          | 101/296 [02:44<06:25,  1.98s/it]

skipping: IDA countries classified as fragile situations, excluding Sub-Saharan Africa

 36%|███████████████████████████████▊                                                         | 106/296 [02:54<06:39,  2.10s/it]

skipping: Gibraltar

 40%|███████████████████████████████████▏                                                     | 117/296 [03:20<07:40,  2.57s/it]

skipping: High income
skipping: Hong Kong SAR, China

 41%|████████████████████████████████████                                                     | 120/296 [03:22<04:52,  1.66s/it]

skipping: Heavily indebted poor countries (HIPC)

 42%|█████████████████████████████████████▎                                                   | 124/296 [03:30<05:22,  1.87s/it]

skipping: IBRD, including blend
skipping: IBRD only
skipping: IDA & IBRD total
skipping: IDA total
skipping: IDA blend

 44%|███████████████████████████████████████                                                  | 130/296 [03:32<02:31,  1.10it/s]

skipping: IDA only

 45%|███████████████████████████████████████▉                                                 | 133/296 [03:37<03:14,  1.19s/it]

skipping: Not classified

 47%|█████████████████████████████████████████▍                                               | 138/296 [03:47<04:52,  1.85s/it]

skipping: Israel

 50%|████████████████████████████████████████████▏                                            | 147/296 [04:07<06:01,  2.43s/it]

Error fetching data for Kiribati (KIR): 400 Client Error: Bad Request for url: https://api.worldbank.org/v2/country/KI/indicator/SP.POP.TOTL?format=jsonstat&per_page=20000

 51%|█████████████████████████████████████████████▍                                           | 151/296 [04:17<05:46,  2.39s/it]

skipping: Latin America & Caribbean (excluding high income)

 53%|███████████████████████████████████████████████▏                                         | 157/296 [04:30<05:31,  2.38s/it]

skipping: Latin America & Caribbean
skipping: Least developed countries: UN classification
skipping: Low income

 55%|████████████████████████████████████████████████▋                                        | 162/296 [04:35<03:24,  1.53s/it]

skipping: Lower middle income
skipping: Low & middle income

 56%|█████████████████████████████████████████████████▌                                       | 165/296 [04:38<02:43,  1.25s/it]

skipping: Late-demographic dividend

 57%|██████████████████████████████████████████████████▊                                      | 169/296 [04:45<03:28,  1.64s/it]

skipping: Macao SAR, China

 59%|████████████████████████████████████████████████████▎                                    | 174/296 [04:55<04:10,  2.06s/it]

skipping: Middle East (developing only)

 60%|█████████████████████████████████████████████████████▏                                   | 177/296 [05:00<03:39,  1.84s/it]

skipping: Middle East & North Africa

 61%|██████████████████████████████████████████████████████                                   | 180/296 [05:05<03:25,  1.77s/it]

skipping: Middle income

 62%|███████████████████████████████████████████████████████▋                                 | 185/296 [05:14<03:40,  1.98s/it]

skipping: Middle East & North Africa (excluding high income)

 66%|██████████████████████████████████████████████████████████▎                              | 194/296 [05:34<04:18,  2.53s/it]

skipping: North America
skipping: North Africa

 69%|█████████████████████████████████████████████████████████████▎                           | 204/296 [05:54<03:33,  2.32s/it]

skipping: Non-resource rich Sub-Saharan Africa countries

 70%|█████████████████████████████████████████████████████████████▉                           | 206/296 [05:56<02:44,  1.83s/it]

skipping: IDA countries not classified as fragile situations, excluding Sub-Saharan Africa

 70%|██████████████████████████████████████████████████████████████▌                          | 208/296 [05:58<02:20,  1.60s/it]

skipping: OECD members

 71%|███████████████████████████████████████████████████████████████▏                         | 210/296 [06:01<02:09,  1.51s/it]

skipping: Other small states

 74%|█████████████████████████████████████████████████████████████████▌                       | 218/296 [06:19<03:00,  2.31s/it]

skipping: Pre-demographic dividend

 75%|███████████████████████████████████████████████████████████████████                      | 223/296 [06:29<02:38,  2.18s/it]

skipping: West Bank and Gaza
skipping: Pacific island small states
skipping: Post-demographic dividend

 77%|████████████████████████████████████████████████████████████████████▊                    | 229/296 [06:37<01:55,  1.72s/it]

skipping: Resource rich Sub-Saharan Africa countries

 78%|█████████████████████████████████████████████████████████████████████▊                   | 232/296 [06:41<01:49,  1.71s/it]

skipping: South Asia

 82%|█████████████████████████████████████████████████████████████████████████                | 243/296 [07:06<02:06,  2.38s/it]

skipping: Sub-Saharan Africa (excluding high income)

 83%|█████████████████████████████████████████████████████████████████████████▋               | 245/296 [07:09<01:33,  1.83s/it]

skipping: Sub-Saharan Africa
skipping: Small states

 86%|████████████████████████████████████████████████████████████████████████████▎            | 254/296 [07:25<01:31,  2.19s/it]

skipping: Sub-Saharan Africa excluding South Africa

 88%|█████████████████████████████████████████████████████████████████████████████▉           | 259/296 [07:37<01:27,  2.37s/it]

skipping: East Asia & Pacific (IDA & IBRD countries)
skipping: Europe & Central Asia (IDA & IBRD countries)

 90%|███████████████████████████████████████████████████████████████████████████████▋         | 265/296 [07:47<01:03,  2.06s/it]

skipping: Latin America & the Caribbean (IDA & IBRD countries)

 90%|████████████████████████████████████████████████████████████████████████████████▎        | 267/296 [07:49<00:49,  1.72s/it]

skipping: Middle East & North Africa (IDA & IBRD countries)

 91%|████████████████████████████████████████████████████████████████████████████████▉        | 269/296 [07:52<00:43,  1.59s/it]

skipping: South Asia (IDA & IBRD)
skipping: Sub-Saharan Africa (IDA & IBRD countries)

 94%|███████████████████████████████████████████████████████████████████████████████████▌     | 278/296 [08:09<00:39,  2.18s/it]

skipping: Upper middle income

 97%|██████████████████████████████████████████████████████████████████████████████████████▌  | 288/296 [08:32<00:19,  2.40s/it]

skipping: World

 98%|███████████████████████████████████████████████████████████████████████████████████████▍ | 291/296 [08:38<00:11,  2.29s/it]

skipping: Sub-Saharan Africa excluding South Africa and Nigeria

100%|█████████████████████████████████████████████████████████████████████████████████████████| 296/296 [08:48<00:00,  1.78s/it]

In [7]:
country

{'id': 'ZWE',
 'iso2Code': 'ZW',
 'name': 'Zimbabwe',
 'region': {'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-Saharan Africa '},
 'adminregion': {'id': 'SSA',
  'iso2code': 'ZF',
  'value': 'Sub-Saharan Africa (excluding high income)'},
 'incomeLevel': {'id': 'LMC',
  'iso2code': 'XN',
  'value': 'Lower middle income'},
 'lendingType': {'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'},
 'capitalCity': 'Harare',
 'longitude': '31.0672',
 'latitude': '-17.8312'}

In [ ]:
'''def is_country(entry):
    if entry['region']['value'] == 'Aggregates' or entry['incomeLevel']['value'] == 'Aggregates':
        return False
    if not entry['capitalCity']:
        return False
    return True
    
pop_data = []
# Fetch the list of countries
countries = wbdata.get_countries()
for country in tqdm(countries):
    

    if is_country(country):
        iso2_code = country['iso2Code']
        #print(f"{country['name']} ({country['id']})")
        
        # Define the indicator for population data
        indicators = {'SP.POP.TOTL': 'Population'}
        try:
            df = wbdata.get_dataframe(indicators, country=iso2_code)
            df['ISO2'] = iso2_code
            pop_data.append(df)
        except Exception as e:
            print(f"Error fetching data for {country['name']} ({country['id']}): {e}")    
        time.sleep(2)
    
    else: 
        print(f"skipping: {country['name']}")'''

In [6]:
popsizes = pd.concat(pop_data).reset_index().drop(columns='Series')
popsizes.head()

  Country  Year SP.POP.TOTL
0   Aruba  1960       54922
1   Aruba  1961       55578
2   Aruba  1962       56320
3   Aruba  1963       57002
4   Aruba  1964       57619

In [ ]:
# Create a list of dictionaries with ISO2 and ISO3 codes
lookup_data = [{'ISO2': country.alpha_2, 'ISO3': country.alpha_3} for country in pycountry.countries]

# Convert the list to a DataFrame
lookup_df = pd.DataFrame(lookup_data)

#add iso3 to population size dataframe
popsizes_iso3 = popsizes.reset_index(names='Year').merge(lookup_df, on='ISO2', how='left')
popsizes_iso3

In [ ]:
cols = ['ISO3', '2022', '2023']
wide_df = popsizes_iso3.pivot(index='ISO3', columns='Year', values='Population').reset_index()[cols]
msno.matrix(wide_df)

In [ ]:
# test all countries are found:

# read in country list 
country_lookup = pd.read_excel('helper/ToVerify_country_codes.xlsx')
country_lookup.head()

In [ ]:
# ensure all the countries are there 
test = popsizes_iso3.merge(country_lookup, on='ISO3', indicator=True, how='outer')
test._merge.value_counts()

In [ ]:

# store population sizes 
country_lookup.head()

In [12]:
data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,83.8,88.70,93.5,97.2,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,AFG,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.0,8.26,11.0,13.5,16.8,17.6,17.0,16.5,17.2,17.7
3,Africa Western and Central,AFW,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Individuals using the Internet (% of population),IT.NET.USER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,21.4,22.00,23.2,26.0,29.0,32.1,36.6,39.4,42.1,44.8

In [11]:
import pandas as pd 
# URL to download the data in Excel format
url = "http://api.worldbank.org/v2/en/indicator/IT.NET.USER.ZS?downloadformat=excel"

# Read the data into a pandas DataFrame
data = pd.read_excel(url, sheet_name='Data', skiprows=3)

# Filter the data for the year 2024
data_2024 = data[['Country Name', '2024']]

# Display the data
print(data_2024)

KeyError: "['2024'] not in index"

In [8]:
import requests

# Define the URL for the World Bank API
url = "http://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?date=2024&format=json"
url = "https://api.internetworldstats.com/v1/population?year=2024"
url = "http://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?date=2024&format=json&per_page=10000"
url = "https://api.internetworldstats.com/v1/population?year=2024"

# Send a request to the API
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()
    # Check if the data is not None and has the expected structure
    if data and len(data) > 1:
        for entry in data[1]:
            country = entry['country']['value']
            population = entry['value']
            print(f"{country}: {population}")
    else:
        print("No data available for the specified year.")
else:
    print("Failed to retrieve data")

Failed to retrieve data

In [7]:
data

[{'page': 0,
  'pages': 0,
  'per_page': 0,
  'total': 0,
  'sourceid': None,
  'lastupdated': None},
 None]

# we are social 

- [ ] cut videos to images
- [ ] extract data from images

In [19]:
# video -> image 

import cv2
import os

def extract_frames(video_path, output_dir):
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Open the video file
    cap = cv2.VideoCapture(video_path)
    frame_count = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Save the frame as an image
        output_path = os.path.join(output_dir, f"frame_{frame_count}.png")
        cv2.imwrite(output_path, frame)
        frame_count += 1

    cap.release()

# Example usage
video_path = 'all_countries.mov'
output_dir = '../data/raw/we are social/'
extract_frames(video_path, output_dir)

OpenCV: Couldn't read video stream from file "all_countries.mov"

In [20]:
print(cv2.getBuildInformation())

General configuration for OpenCV 4.11.0 =====================================
  Version control:               4.11.0

  Platform:
    Timestamp:                   2025-01-16T10:05:12Z
    Host:                        Darwin 22.6.0 x86_64
    CMake:                       3.31.4
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release
    Algorithm Hint:              ALGO_HINT_ACCURATE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3 SSE4_1
      requested:                 DETECT
    Dispatched code generation:  SSE4_2 AVX FP16 AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_2 (1 files):          + POPCNT SSE4_2
      AVX (8 files):             + POPCNT SSE4_2 AVX
      FP16 (0 files):            + POPCNT SSE4_2 AVX FP16
      AVX2 (36 files):           + POPCNT SSE4_2 AVX FP16 AVX2 FMA3
      AVX512_SKX (5 files):      + POPCNT SSE4_2 AVX FP16 AVX2 FMA3 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                /usr/local/opt/ccache/libexec/clang++  (ver 15.0.0.15000100)
    C++ flags (Release):         -arch x86_64   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-copy -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -arch x86_64   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-copy -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/local/opt/ccache/libexec/clang
    C flags (Release):           -arch x86_64   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -arch x86_64   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -ffunction-sections -fdata-sections  -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -arch x86_64  -Wl,-dead_strip
    Linker flags (Debug):        -arch x86_64  -Wl,-dead_strip
    ccache:                      YES
    Precompiled headers:         NO
    Extra dependencies:          -framework OpenCL /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/Accelerate.framework -lm -ldl -framework Cocoa /usr/local/lib/libavif.16.1.1.dylib -framework AppKit
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib ippiw ippicv

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching video videoio
    Disabled:                    java world
    Disabled by dependency:      -
    Unavailable:                 python2 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI:                           COCOA
    Cocoa:                       YES
    VTK support:                 NO

  Media I/O:
    ZLib:                        build (ver 1.3.1)
    JPEG:                        build-libjpeg-turbo (ver 3.0.3-70)
      SIMD Support Request:      YES
      SIMD Support:              YES
    WEBP:                        build (ver decoder: 0x0209, encoder: 0x020f, demux: 0x0107)
    AVIF:                        /usr/local/lib/libavif.16.1.1.dylib (ver 1.1.1)
    PNG:                         build (ver 1.6.43)
      SIMD Support Request:      YES
      SIMD Support:              YES (Intel SSE)
    TIFF:                        build (ver 42 - 4.6.0)
    JPEG 2000:                   build (ver 2.5.0)
    OpenEXR:                     build (ver 2.3.0)
    GIF:                         NO
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    FFMPEG:                      YES
      avcodec:                   YES (61.19.100)
      avformat:                  YES (61.7.100)
      avutil:                    YES (59.39.100)
      swscale:                   YES (8.3.100)
      avresample:                NO
    GStreamer:                   NO
    AVFoundation:                YES

  Parallel framework:            GCD

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2021.9.1 [2021.9.1]
           at:                   /Users/runner/work/opencv-python/opencv-python/_skbuild/macosx-10.16-x86_64-3.9/cmake-build/3rdparty/ippicv/ippicv_mac/icv
    Intel IPP IW:                sources (2021.9.1)
              at:                /Users/runner/work/opencv-python/opencv-python/_skbuild/macosx-10.16-x86_64-3.9/cmake-build/3rdparty/ippicv/ippicv_mac/iw
    Lapack:                      YES (/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/Accelerate.framework -lm -ldl)
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)
    Flatbuffers:                 builtin/3rdparty (23.5.9)

  OpenCL:                        YES (no extra features)
    Include path:                NO
    Link libraries:              -framework OpenCL

  Python 3:
    Interpreter:                 /Users/runner/work/opencv-python/opencv-python/venv/bin/python (ver 3.9.13)
    Libraries:                   /Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib (ver 3.9.13)
    Limited API:                 YES (ver 0x03060000)
    numpy:                       /Users/runner/work/opencv-python/opencv-python/venv/lib/python3.9/site-packages/numpy/_core/include (ver 2.0.2)
    install path:                python/cv2/python-3

  Python (for build):            /Users/runner/work/opencv-python/opencv-python/venv/bin/python

  Java:
    ant:                         /usr/local/bin/ant (ver 1.10.15)
    Java:                        NO
    JNI:                         /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64/Contents/Home/include /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64/Contents/Home/include/darwin /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64/Contents/Home/include
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /Users/runner/work/opencv-python/opencv-python/_skbuild/macosx-10.16-x86_64-3.9/cmake-install
-----------------------------------------------------------------

In [24]:
from moviepy.video.io.VideoFileClip import VideoFileClip
import os
from PIL import Image

In [25]:
def extract_frames(video_path, output_dir):
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Load the video
    clip = VideoFileClip(video_path)
    print('opened video')
    frame_count = 0

    for frame in clip.iter_frames():
        output_path = os.path.join(output_dir, f"frame_{frame_count}.png")
        frame_image = Image.fromarray(frame)
        frame_image.save(output_path)
        frame_count += 1

# Example usage
video_path = 'all_countries.mov'
output_dir = '../data/raw/we are social/'
extract_frames(video_path, output_dir)

{'video_found': False, 'audio_found': False, 'metadata': {}, 'inputs': [{'streams': [None]}], 'video_n_frames': 0, 'video_duration': 0.0}
/Users/brunsd01/BBC Dropbox/Domi Bruns/developing/venv/lib/python3.11/site-packages/imageio_ffmpeg/binaries/ffmpeg-macos-x86_64-v7.1 -i all_countries.mov -loglevel error -f image2pipe -vf scale=1:1 -sws_flags bicubic -pix_fmt rgb24 -vcodec rawvideo -

/Users/brunsd01/BBC Dropbox/Domi Bruns/developing/venv/lib/python3.11/site-packages/moviepy/video/io/ffmpeg_reader.py:178: UserWarning: In file all_countries.mov, 3 bytes wanted but 0 bytes read at frame index 0 (out of a total 0 frames), at time 0.00/0.00 sec. Using the last valid frame instead.
  warnings.warn(

OSError: MoviePy error: failed to read the first frame of video file all_countries.mov. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.

In [14]:
from PIL import Image
import pytesseract

In [16]:
img = Image.open("../data/raw/we are social/1.png")
text = pytesseract.image_to_string(img)

TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

In [ ]:
# Function to extract values from an image
def extract_values(image_path, image_file):
    # Open the image
    img = Image.open(image_path+image_file)
    
    # Use pytesseract to extract text
    text = pytesseract.image_to_string(img)
    
    # Extract the required values from the text
    lines = text.split('\n')
    values = {}
    for line in lines:
        if "ABKHAZIA" in line:
            values["country"] = "Abkhazia"
        elif "INDIVIDUALS USING THE INTERNET" in line:
            values["Individuals using the internet"] = int(line.split()[0].replace(',', ''))
        elif "TOTAL VS POPULATION" in line:
            values["Total vs Population"] = float(line.split()[0].replace('%', ''))
    
    return values

# List of image paths
path = "../data/raw/we are social/"
images = ["1.png", "2.png"]

# Iterate through the list of images and extract values
extracted_data = []
for image_file in images:
    extracted_data.append(extract_values(path, image_file))

print(extracted_data)

TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.