In [1]:
platformID = 'INS'

In [2]:
from datetime import datetime
import pandas as pd
import numpy as np
import os 

import psycopg2

## import helper

In [3]:
import sys
from pathlib import Path

try:
    # Works in Python scripts
    helper_path = Path(__file__).resolve().parent.parent / "helper"
except NameError:
    # Works in Jupyter notebooks
    helper_path = Path().resolve().parent / "helper"

sys.path.insert(0, str(helper_path))

# Now import your modules 
from config import gam_info
from functions import execute_sql_query
import test_functions

In [4]:
# country
country_codes = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='CountryID', 
                              keep_default_na=False)

# week 
week_tester = pd.read_excel(f"../../{gam_info['lookup_file']}", sheet_name='GAM Period')
week_tester['w/c'] = pd.to_datetime(week_tester['w/c'])
week_tester['week_ending'] = pd.to_datetime(week_tester['week_ending'])

# social media accounts
socialmedia_accounts = pd.read_excel("../helper/ins_account_lookup.xlsx")
channel_ids = socialmedia_accounts['Channel ID'].tolist()

# ingestion

# activity

In [5]:
metric_ids = ['saved', 
              'shares', 
              'total_interactions', 
              'comments', 
              #'engagement',
              'impressions', 
              'likes', 
              'reach', 
              'plays', 
              #'video_views'
             ]

# content level / post level
sql_query = f""" 
    SELECT 
        ig_user_id, 
        ig_media_id, 
        ig_metric_id, 
        ig_metric_period, 
        ig_metric_end_time, 
        ig_metric_breakdown, 
        ig_metric_value
    FROM 
        redshiftdb.central_insights.ig_media_insights
    WHERE
        ig_metric_period = 'weekdiff'
        AND
        ig_metric_end_time BETWEEN '{gam_info['weekEnding_start']}' and '{gam_info['weekEnding_end']}'
    ;
    """
file = f"../data/raw/{platformID}/{gam_info['file_timeinfo']}_{platformID}_activity_redshift_extract.csv"
df = execute_sql_query(sql_query)

df['ig_user_id'] = df['ig_user_id'].astype(str) 
df['ig_media_id'] = df['ig_media_id'].astype(str) 
df.to_csv(file, index=False, na_rep='')

"df = execute_sql_query(sql_query)\n\ndf['ig_user_id'] = df['ig_user_id'].astype(str) \ndf['ig_media_id'] = df['ig_media_id'].astype(str) \ndf.to_csv(file, index=False, na_rep='')"

In [6]:
ig_views = pd.read_csv(file, keep_default_na=False)

ig_views['ig_user_id'] = ig_views['ig_user_id'].astype(str) 
ig_views['ig_media_id'] = ig_views['ig_media_id'].astype(str) 
ig_views['ig_metric_end_time'] = pd.to_datetime(ig_views['ig_metric_end_time'])
# Run the tests
column_name = 'ig_user_id'
test_functions.test_filter_elements_returned(ig_views, channel_ids, column_name, 
                                             "1_IG_1", "ig_media_insights sql query - user test")
column_name = 'ig_metric_id'
test_functions.test_filter_elements_returned(ig_views, metric_ids, column_name, 
                                             "1_IG_2", "ig_media_insights sql query - metric test")

test_functions.test_weeks_presence('week_ending', 
                                    ig_views.rename(columns={'ig_metric_end_time': 'week_ending'}), 
                                    week_tester, '1_IG_3', "ig_media_insights sql query")

...testing ig_user_id...
Fail - not all elements were retrieved
...updating logbook...

...testing ig_metric_id...
Pass - everything found!
...updating logbook...

All weeks are present in the dataset.
...updating logbook...

# metadata

In [7]:
sql_query = f""" 
    SELECT 
        ig_user_id, 
        ig_user_name, 
        ig_media_id, 
        ig_media_type, 
        ig_media_product_type, 
        week_ending, 
        ig_media_created_time, 
        ig_user_bbc_bus_unit
    FROM 
        redshiftdb.central_insights.ig_media_metadata
    WHERE
        week_ending BETWEEN '{gam_info['weekEnding_start']}' and '{gam_info['weekEnding_end']}'
    ;
    """

file = f"../data/raw/{platformID}/{gam_info['file_timeinfo']}_{platformID}_metadata_redshift_extract.csv"
'''df = execute_sql_query(sql_query)
df['ig_user_id'] = df['ig_user_id'].astype(str) 
df['ig_media_id'] = df['ig_media_id'].astype(str) 

df.to_csv(file, index=False, na_rep='')
'''
ig_metadata = pd.read_csv(file, keep_default_na=False)

ig_metadata['ig_user_id'] = ig_metadata['ig_user_id'].astype(str) 
ig_metadata['ig_media_id'] = ig_metadata['ig_media_id'].astype(str) 
ig_metadata['week_ending'] = pd.to_datetime(ig_metadata['week_ending'])
# Run the tests
column_name = 'ig_user_id'
test_functions.test_filter_elements_returned(ig_metadata, channel_ids, column_name, 
                                             "1_IG_4", "ig_media_metadata sql query - channel test")

test_functions.test_weeks_presence('week_ending', ig_metadata, week_tester, 
                                   '1_IG_5', "ig_media_insights sql query")

ig_metadata.sample()

...testing ig_user_id...
Fail - not all elements were retrieved
...updating logbook...

All weeks are present in the dataset.
...updating logbook...

,ig_user_id,ig_user_name,ig_media_id,ig_media_type,ig_media_product_type,week_ending,ig_media_created_time,ig_user_bbc_bus_unit
1713582,17841414820810768,BBC Sport Wales,18159920608306632,IMAGE,FEED,2025-02-23,2025-01-30 21:03:05,None

# combine media metrics and their metadata

In [8]:
ig_views = ig_views.rename(columns={'ig_metric_end_time': 'week_ending'})
ig_views['week_ending'] = pd.to_datetime(ig_views['week_ending'])
ig_metadata['week_ending'] = pd.to_datetime(ig_metadata['week_ending'])
left_cols = ['ig_media_id', 'ig_metric_id', 'ig_metric_period', 'week_ending', 'ig_metric_breakdown', 'ig_metric_value']

ig_combine = ig_views[left_cols].merge(ig_metadata, how='inner', on=['ig_media_id', 'week_ending'])
test_functions.test_inner_join(ig_views, ig_metadata, ['ig_media_id', 'week_ending'],
                               '1_IG_6', test_step="combining ig_media_insights & ig_media_metadata ")

ig_combine.columns

Inner join test 1_IG_6 successful: No issues found.
...updating logbook...

Index(['ig_media_id', 'ig_metric_id', 'ig_metric_period', 'week_ending',
       'ig_metric_breakdown', 'ig_metric_value', 'ig_user_id', 'ig_user_name',
       'ig_media_type', 'ig_media_product_type', 'ig_media_created_time',
       'ig_user_bbc_bus_unit'],
      dtype='object')

## processing

In [9]:
# to get to account level 
# summarised are these columns: 
#     'ig_media_id', 'ig_media_type', 'ig_media_product_type', 'ig_media_created_time', 
ig_media_to_user = ig_combine.groupby(['ig_user_id', 'ig_user_name', 'ig_user_bbc_bus_unit', 
                                 'week_ending',
                                 'ig_metric_id', 'ig_metric_period', 'ig_metric_breakdown'])['ig_metric_value'].sum().reset_index()

# Rename the column for sum
ig_media_to_user.rename(columns={'ig_metric_value': 'Sum_ig_metric_value'}, inplace=True)

# Perform crosstab operation
ig_media_to_user = pd.pivot_table(ig_media_to_user, 
                             values='Sum_ig_metric_value', 
                             index=['ig_user_id', 'ig_user_name', 'ig_user_bbc_bus_unit', 
                                    'week_ending', 
                                    'ig_metric_period', 'ig_metric_breakdown'],
                             columns='ig_metric_id', 
                             aggfunc='sum').reset_index()

# test there is now one row per channel / week
test_functions.test_duplicates(ig_media_to_user, ['ig_user_id', 'week_ending'], 
                               "1_IG_7", "bringing IG media level to account level")

Pass - No combinations occurs more than once a week.
...updating logbook...

## user insights

In [10]:
# account level (would also contain content level but we don't what this here wil be replaced )

metric_ids = ['impressions', 'reach']
formatted_metric_ids = ', '.join(f"'{metric_id}'" for metric_id in metric_ids)

sql_query = f""" 
    SELECT 
        ig_user_id, 
        ig_user_name, 
        ig_metric_id, 
        ig_metric_period, 
        ig_metric_breakdown, 
        ig_metric_end_time, 
        ig_metric_value
    FROM 
        redshiftdb.central_insights.ig_user_insights
    WHERE
         (
         ig_metric_id in ({formatted_metric_ids}) 
         AND
         ig_metric_end_time BETWEEN '{gam_info['weekEnding_start']}' and '{gam_info['weekEnding_end']}')
    ;
    """
file = f"../data/raw/{platformID}/{gam_info['file_timeinfo']}_{platformID}_userInsights_redshift_extract.csv"
'''df = execute_sql_query(sql_query)
df['ig_user_id'] = df['ig_user_id'].astype(str) 
df.to_csv(file, index=False, na_rep='')
'''
ig_userInsights = pd.read_csv(file, keep_default_na=False)
ig_userInsights['ig_user_id'] = ig_userInsights['ig_user_id'].astype(str) 
ig_userInsights['ig_metric_end_time'] = pd.to_datetime(ig_userInsights['ig_metric_end_time'])
# Run the tests
column_name = 'ig_user_id'
test_functions.test_filter_elements_returned(ig_userInsights, channel_ids, column_name, "1_IG_8", "ig_user_insights sql query - user test")

column_name = 'ig_metric_id'
test_functions.test_filter_elements_returned(ig_userInsights, metric_ids, column_name, "1_IG_9", "ig_user_insights sql query - metric test")

test_functions.test_weeks_presence('week_ending', ig_userInsights.rename(columns={'ig_metric_end_time': 'week_ending'}), 
                                   week_tester, '1_IG_10', "ig_user_insights sql query")

...testing ig_user_id...
Fail - not all elements were retrieved
...updating logbook...

...testing ig_metric_id...
Pass - everything found!
...updating logbook...

All weeks are present in the dataset.
...updating logbook...

In [11]:
# Pivot the DataFrame
ig_user_by_userInsights = ig_userInsights.pivot_table(index=['ig_user_id', 'ig_user_name', 'ig_metric_period',
                                                             'ig_metric_breakdown', 'ig_metric_end_time'],
                                                      columns='ig_metric_id',
                                                      values='ig_metric_value',
                                                      aggfunc='sum').reset_index()

# Flatten the column headers
ig_user_by_userInsights.columns.name = None
ig_user_by_userInsights.columns = [col if isinstance(col, str) else col[1] for col in ig_user_by_userInsights.columns]
#ig_user_by_userInsights.sample()
ig_user_by_userInsights = ig_user_by_userInsights.rename(columns={'ig_metric_end_time': 'week_ending'})
ig_user_by_userInsights['week_ending'] = pd.to_datetime(ig_user_by_userInsights['week_ending'])

# test there is now one row per channel / week
test_functions.test_duplicates(ig_user_by_userInsights, ['ig_user_id', 'week_ending'], 
                               "1_IG_11", "get unique user entries per channel & week")

'''
ig_user_by_userInsights_allWeeks = joining_allWeeks_perChannel(ig_user_by_userInsights, 'week_ending', 'ig_user_id',
                                                  week_tester, 
                                                  ['ig_user_id', 'ig_user_name', 'ig_metric_period', 'ig_metric_breakdown']
                                                              )'''

Pass - No combinations occurs more than once a week.
...updating logbook...

"\nig_user_by_userInsights_allWeeks = joining_allWeeks_perChannel(ig_user_by_userInsights, 'week_ending', 'ig_user_id',\n                                                  week_tester, \n                                                  ['ig_user_id', 'ig_user_name', 'ig_metric_period', 'ig_metric_breakdown']\n                                                              )"

# combine

In [12]:

# excluded from left 'impressions', 'reach'
left_cols = ['ig_user_id', 'ig_user_name', 'ig_user_bbc_bus_unit', 
             'week_ending','ig_metric_period', 'ig_metric_breakdown',
             'comments', 'likes', 'plays',
             'saved', 'shares', 'total_interactions', #'video_views', 'engagement'
            ] 
# excluded from right #'ig_user_name', 'ig_metric_period', 'ig_metric_breakdown',
right_cols = ['ig_user_id', 'week_ending', 'impressions', 'reach']
ig_user_by_allMetrics = ig_media_to_user[left_cols].merge(ig_user_by_userInsights[right_cols], 
                                                                how='outer', #indicator=True,
                                                                on=['ig_user_id', 'week_ending']
                                                               )
test_functions.test_inner_join(ig_media_to_user[left_cols], 
                               ig_user_by_userInsights[right_cols], 
                               ['ig_user_id', 'week_ending'],
                               "1_IG_12", test_step="joining user insights to media insights")

Inner join test 1_IG_12 failed: Issues found.
Issues with df_left (rows present in df_left but not in df_right)
Issues with df_right (rows present in df_right but not in df_left)
...updating logbook...

# user metadata redshift query

In [13]:
sql_query = f""" 
    SELECT 
        ig_user_id, 
        ig_user_ig_id, 
        ig_user_name, 
        ig_user_username, 
        ig_user_linked_fb_page_id, 
        ig_user_bbc_category, 
        ig_user_bbc_nation, 
        ig_user_bbc_clean_name, 
        ig_user_bbc_bus_unit, 
        week_ending
    FROM 
        redshiftdb.central_insights.ig_user_metadata
    WHERE
        (
        week_ending BETWEEN '{gam_info['weekEnding_start']}' and '{gam_info['weekEnding_end']}')
    ;
    """
file = f"../data/raw/{platformID}/{gam_info['file_timeinfo']}_{platformID}_userMetadata_redshift_extract.csv"

'''df = execute_sql_query(sql_query)

df['ig_user_id'] = df['ig_user_id'].astype(str) 
df['ig_user_ig_id'] = df['ig_user_ig_id'].astype(str) 
df['ig_user_linked_fb_page_id'] = df['ig_user_linked_fb_page_id'].astype(str) 

df.to_csv(file, index=False, na_rep='')
'''
ig_userMetadata = pd.read_csv(file, keep_default_na=False)

ig_userMetadata['ig_user_id'] = ig_userMetadata['ig_user_id'].astype(str) 
ig_userMetadata['ig_user_ig_id'] = ig_userMetadata['ig_user_ig_id'].astype(str) 
ig_userMetadata['ig_user_linked_fb_page_id'] = ig_userMetadata['ig_user_linked_fb_page_id'].astype(str) 
ig_userMetadata['week_ending'] = pd.to_datetime(ig_userMetadata['week_ending'])
# Run the tests
column_name = 'ig_user_id'
test_functions.test_filter_elements_returned(ig_userMetadata, channel_ids, 
                                             column_name, "1_IG_13", "ig_user_metadata sql query - user test")

test_functions.test_weeks_presence('week_ending', ig_userMetadata, 
                                   week_tester, '1_IG_14', "ig_user_insights sql query")

ig_userMetadata.sample()

...testing ig_user_id...
Fail - not all elements were retrieved
...updating logbook...

All weeks are present in the dataset.
...updating logbook...

,ig_user_id,ig_user_ig_id,ig_user_name,ig_user_username,ig_user_linked_fb_page_id,ig_user_bbc_category,ig_user_bbc_nation,ig_user_bbc_clean_name,ig_user_bbc_bus_unit,week_ending
5357,17841401143954624,1575974131,BBC News ไทย,bbcthai,1526071940947174,World Service,International,None,Thai,2024-11-24

In [14]:
# just a clean list of the overview columns 
# groupby
cols = ['ig_user_id', 'ig_user_ig_id', 'ig_user_name', 'ig_user_username',
        'ig_user_linked_fb_page_id', 'ig_user_bbc_category', 'ig_user_bbc_nation', 
        'ig_user_bbc_clean_name', 'ig_user_bbc_bus_unit']

ig_userMetadata_slim = ig_userMetadata[cols].drop_duplicates()
ig_userMetadata_slim.shape

(196, 9)

In [15]:
# combine all

# left out 'ig_user_name', 'ig_user_bbc_bus_unit'
right_cols = ['ig_user_id', 'ig_user_ig_id',  'ig_user_username',
       'ig_user_linked_fb_page_id', 'ig_user_bbc_category',
       'ig_user_bbc_nation', 'ig_user_bbc_clean_name', ]
ig_combine_final = ig_user_by_allMetrics.merge(ig_userMetadata_slim[right_cols], how='inner', 
                                               on=['ig_user_id'])
'''test_functions.test_inner_join(ig_user_by_allMetrics, ig_userMetadata_slim[right_cols], 
                               'ig_user_id', '1_IG_15', 'combine user metadata to rest')
'''
ig_combine_final.to_csv(f"../data/raw/{platformID}/{gam_info['file_timeinfo']}_{platformID}_REDSHIFT.csv", 
                          index=None)

### milestone II

In [16]:
ig_engagements = ig_combine_final.merge(week_tester[['week_ending', 'w/c']], on='week_ending', how='left')
print(ig_engagements.shape)
ig_engagements = ig_engagements[ig_engagements['w/c'] >= "2024-04-01"]
print(ig_engagements.shape)


cols = ['w/c', 'ig_user_id', 'ig_user_name', 'ig_user_bbc_bus_unit', 
       'ig_metric_period', 'ig_metric_breakdown', 
        'comments', 'likes', 'plays', 'saved', 'shares', 'total_interactions', 'impressions', 
        'reach', 
        'ig_user_ig_id', 'ig_user_username', 'ig_user_linked_fb_page_id',
       'ig_user_bbc_category', 'ig_user_bbc_nation', 'ig_user_bbc_clean_name',
       ]
ig_engagements['total_interactions'] = ig_engagements['total_interactions'].fillna(0)
ig_engagements['comments'] = ig_engagements['comments'].fillna(0)
ig_engagements['likes'] = ig_engagements['likes'].fillna(0)
ig_engagements['shares'] = ig_engagements['shares'].fillna(0)
ig_engagements['saved'] = ig_engagements['saved'].fillna(0)

ig_engagements['weekly_media_engagements'] = ig_engagements[cols].apply(
    lambda row: row['total_interactions'] 
    if row['total_interactions'] > (row['comments'] + row['likes'] + row['shares'] + row['saved']) 
    else (row['comments'] + row['likes'] + row['shares'] + row['saved']), axis=1
)
ig_engagements['daily_avg_reach'] = 0

cols = ['Channel ID', 'IG FB Linked ID', 'Channel Name', 'IG Account URL',	
         'IG studios exc uk', 'ServiceID', 'ServiceName',]
ig_engagements = ig_engagements.rename(columns={"ig_user_name":"Channel Name",
                                                "ig_user_id": "Channel ID"})\
                                .merge(socialmedia_accounts[cols], on='Channel Name', how='left', 
                                       indicator=True)
ig_engagements['Channel ID'] = ig_engagements['Channel ID_x'].fillna('Channel ID_y')
ig_engagements = ig_engagements.drop(columns=['Channel ID_x', 'Channel ID_y'])

(8908, 21)
(8908, 21)

In [17]:
ig_engagements_name_matched = ig_engagements[ig_engagements['_merge'] == 'both']
ig_engagements_unmatched = ig_engagements[ig_engagements['_merge'] == 'left_only']

ig_engagements_id_matched = ig_engagements_unmatched.merge(socialmedia_accounts[cols], 
                                                           on='Channel ID', how='inner')
cols_to_clean = ['IG FB Linked ID', 'Channel Name', 'IG studios exc uk', 'IG Account URL',
                 'ServiceID', 'ServiceName',]
for col in cols_to_clean:
    ig_engagements_id_matched[f"{col}"] = ig_engagements_id_matched[f"{col}_x"].fillna(ig_engagements_id_matched[f"{col}_y"])
    ig_engagements_id_matched = ig_engagements_id_matched.drop(columns=[f"{col}_x", f"{col}_y"])

ig_engagements_final = pd.concat([ig_engagements_name_matched, ig_engagements_id_matched])

ig_engagements_final['ig_user_linked_fb_page_id'] = ig_engagements_final['ig_user_linked_fb_page_id'].fillna(ig_engagements_final['IG FB Linked ID'])
ig_engagements_final = ig_engagements_final.drop(columns=['IG FB Linked ID'])

cols = ['Channel ID', 'Channel Name', 'ig_user_linked_fb_page_id', 'IG Account URL', 
        'w/c', 'ServiceID', 'IG studios exc uk', 
        'weekly_media_engagements', 'saved', 'plays', 'daily_avg_reach', 'reach', 'impressions']

ig_engagements_final = ig_engagements_final[cols]
ig_engagements_final.to_csv(f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_{platformID}_REDSHIFT.csv", 
                          index=None)

### Milestone III

In [18]:

# Define the multiplier mapping
service_multipliers = {
    "AZE": 0.79,
    "INO": 0.71,
    "SPA": 0.76,
    "RUS": 0.68,
    "UKR": 0.76,
    "URD": 0.81
}

ig_engagements_final['plays'] = ig_engagements_final['plays'].fillna(0)
ig_engagements_final['impressions'] = ig_engagements_final['impressions'].fillna(0)
ig_engagements_final['reach'] = ig_engagements_final['reach'].fillna(0)

# Apply the logic to create a new column 'adjusted_reels_plays'
ig_engagements_final['30 view'] = ig_engagements_final.apply(
    lambda row: row['plays'] * service_multipliers.get(row['ServiceID'], 0.668476004281482),
    axis=1
)

def safe_ratio(row):
    if row['reach'] == 0 or pd.isna(row['reach']):
        return None  # or np.nan if you prefer
    if row['ServiceID'] == 'PER':
        return (row['impressions'] / row['reach']) * 0.052990833 + 1.693711126
    else:
        return (row['impressions'] / row['reach']) * 0.21907280062318 + 1.20241835848198

ig_engagements_final['IG Modelled Factor'] = ig_engagements_final.apply(safe_ratio, axis=1)

def compute_engagement_estimate(row):
    if row['ServiceID'] == 'PER':
        if row['IG Account URL'] == 'instagram.com/bbcpersian':
            factor = row.get('IG Modelled Factor', None)
            if factor and factor != 0:
                return (row['weekly_media_engagements'] + row['30 view']) / factor
            else:
                return None
        else:
            return row.get('IG Engaged Users', None)
    else:
        factor = row.get('IG Modelled Factor', None)
        if factor and factor != 0:
            estimate = (row['weekly_media_engagements'] + row['30 view']) / factor
            return min(estimate, row['reach'])
        else:
            return None

ig_engagements_final['IG Engaged Users'] = ig_engagements_final.apply(compute_engagement_estimate, axis=1)


def compute_persian_engagement(row):
    if row['IG Account URL'] == 'instagram.com/bbcpersian':
        factor = row.get('IG Modelled Factor', None)
        if factor and factor != 0:
            return (row['weekly_media_engagements'] + row['30 view']) / factor
        else:
            return None
    else:
        return row.get('IG Engaged Users', None)

ig_engagements_final['IG Engaged Persian Exception'] = ig_engagements_final.apply(compute_persian_engagement, axis=1)
ig_engagements_final['IG Engaged Persian Exception'] = ig_engagements_final.apply(
    lambda row: row['reach'] if row['IG Engaged Persian Exception'] > row['reach'] 
                             else row['IG Engaged Persian Exception'],
    axis=1
)
ig_engagements_final.to_csv(f"../data/processed/{platformID}/{gam_info['file_timeinfo']}_{platformID}_engagements_final.csv", 
                          index=None)

In [19]:
ig_engagements_final[(ig_engagements_final['Channel ID'] =='17841401606325704')]

,Channel ID,Channel Name,ig_user_linked_fb_page_id,IG Account URL,w/c,ServiceID,IG studios exc uk,weekly_media_engagements,saved,plays,daily_avg_reach,reach,impressions,30 view,IG Modelled Factor,IG Engaged Users,IG Engaged Persian Exception
2524,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-04-01,GNL,no,3764.0,147.0,0.0,0,95276.0,142691.0,0.000000,1.530515,2459.303228,2459.303228
2525,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-04-08,GNL,no,14546.0,609.0,0.0,0,110889.0,192750.0,0.000000,1.583216,9187.627558,9187.627558
2526,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-04-15,GNL,no,4885.0,288.0,0.0,0,67964.0,96576.0,0.000000,1.513718,3227.153087,3227.153087
2527,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-04-22,GNL,no,5356.0,198.0,0.0,0,66010.0,95769.0,0.000000,1.520255,3523.093645,3523.093645
2528,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-04-29,GNL,no,590.0,40.0,0.0,0,46809.0,57825.0,0.000000,1.473048,400.530163,400.530163
2529,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-05-06,GNL,no,13763.0,1056.0,0.0,0,161928.0,190699.0,0.000000,1.460416,9424.030238,9424.030238
2530,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-05-13,GNL,no,469.0,30.0,0.0,0,26153.0,28884.0,0.000000,1.444368,324.709580,324.709580
2531,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-05-20,GNL,no,3063.0,90.0,0.0,0,47658.0,79719.0,0.000000,1.568868,1952.362907,1952.362907
2532,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-05-27,GNL,no,3682.0,187.0,0.0,0,58246.0,79485.0,0.000000,1.501375,2452.419373,2452.419373
2533,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-06-03,GNL,no,264.0,12.0,0.0,0,4025.0,6416.0,0.000000,1.551629,170.143813,170.143813
2534,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-06-10,GNL,no,178.0,7.0,0.0,0,40822.0,52595.0,0.000000,1.484671,119.891849,119.891849
2535,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-06-17,GNL,no,112.0,3.0,0.0,0,21954.0,23901.0,0.000000,1.440920,77.728133,77.728133
2536,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-06-24,GNL,no,103.0,9.0,0.0,0,1912.0,3827.0,0.000000,1.640908,62.770137,62.770137
2537,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-07-01,GNL,no,5953.0,181.0,0.0,0,68386.0,113657.0,0.000000,1.566516,3800.153547,3800.153547
2538,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-07-08,GNL,no,5321.0,209.0,0.0,0,63228.0,87724.0,0.000000,1.506365,3532.344266,3532.344266
2539,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-07-15,GNL,no,3463.0,109.0,0.0,0,66843.0,95891.0,0.000000,1.516694,2283.255932,2283.255932
2540,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-07-22,GNL,no,3756.0,273.0,0.0,0,79107.0,91578.0,0.000000,1.456027,2579.621818,2579.621818
2541,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-07-29,GNL,no,277.0,27.0,0.0,0,26669.0,35221.0,0.000000,1.491742,185.688989,185.688989
2542,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-08-05,GNL,no,2015.0,54.0,0.0,0,69212.0,110391.0,0.000000,1.551833,1298.464711,1298.464711
2543,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-08-12,GNL,no,6333.0,191.0,0.0,0,42709.0,61254.0,0.000000,1.516616,4175.742716,4175.742716
2544,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-08-19,GNL,no,2885.0,76.0,0.0,0,70034.0,86111.0,0.000000,1.471781,1960.209453,1960.209453
2545,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-08-26,GNL,no,2306.0,108.0,0.0,0,60504.0,80765.0,0.000000,1.494852,1542.627466,1542.627466
2546,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-09-02,GNL,no,4326.0,151.0,0.0,0,51205.0,66486.0,0.000000,1.486869,2909.470294,2909.470294
2547,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-09-09,GNL,no,2627.0,58.0,0.0,0,51663.0,65256.0,0.000000,1.479131,1776.042605,1776.042605
2548,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-09-16,GNL,no,5018.0,254.0,0.0,0,109092.0,176230.0,0.000000,1.556314,3224.284763,3224.284763
2549,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-09-23,GNL,no,8254.0,457.0,0.0,0,95742.0,159878.0,0.000000,1.568244,5263.210097,5263.210097
2550,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-09-30,GNL,no,2806.0,106.0,0.0,0,78436.0,115298.0,0.000000,1.524447,1840.667203,1840.667203
2551,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-10-07,GNL,no,11303.0,1120.0,0.0,0,105705.0,144246.0,0.000000,1.501367,7528.471956,7528.471956
2552,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-10-14,GNL,no,7334.0,552.0,0.0,0,105347.0,157262.0,0.000000,1.529450,4795.187085,4795.187085
2553,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-10-21,GNL,no,13515.0,1318.0,0.0,0,184969.0,251235.0,0.000000,1.499975,9010.150148,9010.150148
2554,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-10-28,GNL,no,7745.0,682.0,0.0,0,112400.0,189197.0,0.000000,1.571172,4929.441002,4929.441002
2555,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-11-04,GNL,no,530.0,39.0,0.0,0,8446.0,13525.0,0.000000,1.553231,341.224299,341.224299
2556,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-11-11,GNL,no,15266.0,1326.0,213525.0,0,228770.0,252048.0,142736.338814,1.443782,109436.390333,109436.390333
2557,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-11-18,GNL,no,9115.0,719.0,112363.0,0,162506.0,204050.0,75111.969269,1.477496,57006.554349,57006.554349
2558,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-11-25,GNL,no,5119.0,411.0,71146.0,0,59498.0,66513.0,47559.393801,1.447321,36397.185585,36397.185585
2559,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-12-02,GNL,no,1060.0,80.0,14908.0,0,14875.0,18816.0,9965.640272,1.479533,7452.110576,7452.110576
2560,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-12-09,GNL,no,651.0,67.0,6913.0,0,54893.0,58237.0,4621.174618,1.434837,3674.407296,3674.407296
2561,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-12-16,GNL,no,418.0,24.0,3912.0,0,78130.0,117150.0,2615.078129,1.530901,1981.236783,1981.236783
2562,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-12-23,GNL,no,364.0,34.0,3914.0,0,53386.0,73258.0,2616.415081,1.503037,1982.928409,1982.928409
2563,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2024-12-30,GNL,no,540.0,45.0,6628.0,0,80331.0,134789.0,4430.658956,1.570005,3166.014699,3166.014699
2564,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-01-06,GNL,no,4263.0,145.0,4372.0,0,103405.0,186769.0,2922.577091,1.598105,4496.310164,4496.310164
2565,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-01-13,GNL,no,14369.0,2775.0,8951.0,0,315370.0,450419.0,5983.528714,1.515303,13431.322648,13431.322648
2566,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-01-20,GNL,no,4934.0,1025.0,7978.0,0,138125.0,219623.0,5333.101562,1.550751,6620.729273,6620.729273
2567,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-01-27,GNL,no,3000.0,699.0,7521.0,0,504235.0,786978.0,5027.608028,1.544333,5198.105934,5198.105934
2568,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-02-03,GNL,no,680.0,158.0,1454.0,0,581033.0,893692.0,971.964110,1.539376,1073.138678,1073.138678
2569,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-02-10,GNL,no,227.0,51.0,1371.0,0,590758.0,933876.0,916.480602,1.548731,738.334009,738.334009
2570,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-02-17,GNL,no,168.0,46.0,0.0,0,579297.0,897971.0,0.000000,1.542004,108.949124,108.949124
2571,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-02-24,GNL,no,111.0,13.0,0.0,0,388755.0,566439.0,0.000000,1.521620,72.948550,72.948550
2572,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-03-03,GNL,no,47.0,6.0,0.0,0,81610.0,140404.0,0.000000,1.579317,29.759700,29.759700
2573,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-03-10,GNL,no,61.0,9.0,0.0,0,87931.0,181936.0,0.000000,1.655697,36.842494,36.842494
2574,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-03-17,GNL,no,51.0,2.0,0.0,0,143605.0,216670.0,0.000000,1.532954,33.269110,33.269110
2575,17841401606325704,BBC Travel,133536249999517,instagram.com/bbc_travel,2025-03-24,GNL,no,55.0,11.0,0.0,0,134470.0,220892.0,0.000000,1.562286,35.204817,35.204817